RWBuild/package_MurugoAuth_API-Laravel

- src/Http/Controllers/AuthenticationController.php
- src/routes/api.php
fix: error while getting response from Murugo on userFromToken method
> fix: error while getting response from Murugo on userFromToken method

- src/Http/Controllers/AuthenticationController.php
> fix: Update - AVATAR

- src/Http/Controllers/AuthenticationController.php
return user model instead of user json object on facades
> fix: return user model instead of user json object on facades

- src/Http/Controllers/AuthenticationController.php
use save method instead of update on facades
> fix: use save method instead of update on facades

- src/Http/Controllers/AuthenticationController.php
- src/MurugoAuthServiceProvider.php
- src/database/migrations/2020_06_05_141302_remove_email_from_murugo_users.php
fix: remove email in request and in migration
> fix: remove email in request and in migration

- src/MurugoAuthServiceProvider.php
fix: load new migration of deleting email
> fix: load new migration of deleting email

- src/Models/MurugoUser.php
> fix: make timestamps false

- src/Facades/MurugoAuth2.php
- src/MurugoAuth2ServiceProvider.php
- src/MurugoAuthHandler.php
- src/MurugoUserFormatter.php
- src/database/migrations/2020_06_25_151435_add_refresh_token_to_murugo_users.php
restructured supports of laravel passports packages
> restructured supports of laravel passports packages

- composer.json
- src/Exceptions/MurugoAuthDenied.php
- src/Exceptions/MurugoInvalidSateRequest.php
- src/Facades/MurugoAuth2.php
- src/MurugoAuth2ServiceProvider.php
- src/MurugoAuthHandler.php
- src/MurugoAuthServiceProvider.php
- src/MurugoUserFormatter.php
- src/database/migrations/2020_06_25_151435_add_refresh_token_to_murugo_users.php
new structure of authenticating using passport approach
> feat: new structure of authenticating using passport approach

- src/Facades/MurugoAuth2.php
- src/MurugoAuth2ServiceProvider.php
- src/MurugoUserFormatter.php
> fix: remove typo on second facades

- composer.json
remove typo in composer json file
> fix: remove typo in composer json file

- README.md
- src/Models/MurugoUser.php
- src/MurugoAuthHandler.php
- src/MurugoUserFormatter.php
- src/Traits/MurugoAuthHelper.php
add refreshToken method and update READ.ME file
> feat: add refreshToken method and update READ.ME file

- src/MurugoAuthHandler.php
add app_key in redirect method of passport
> feat: add app_key in redirect method of passport

- src/database/migrations/2020_06_25_151435_add_refresh_token_to_murugo_users.php
fix: add deleted migration of token
> fix: add deleted migration of token

- src/MurugoAuthHandler.php
add header in getting thirdparty me endpoint
> feat: add header in getting thirdparty me endpoint

- src/MurugoAuthHandler.php
add APPKEY using self in static method
> fix: add APPKEY using self in static method

- src/Models/MurugoUser.php
- src/MurugoUserFormatter.php
- src/database/migrations/2020_06_25_151435_add_refresh_token_to_murugo_users.php
add murugo user id which is not hashed in response
> feat: add murugo user id which is not hashed in response

- src/MurugoUserFormatter.php
set murugo user id attribute as array
> fix: set murugo user id attribute as array

- src/MurugoUserFormatter.php
check condition of hashedMurugoUserId and MurugoUserId
> fix: check condition of hashedMurugoUserId and MurugoUserId

- README.md
- composer.json
- composer.lock
Remove useless dependencies 
- remove doctrine/dbal
- remove guzzle
> Fix deprecated package

- README.md
- src/MurugoAuthHandler.php
- src/MurugoUserFormatter.php
Support the use of the invite token directly from the murugo user formatted response via callback
> Ft support invite service and access user details via callback

- README.md
- This pull request does not contain any additional information or change to existing information.
- This pull request is intended to improve the wording and grammar used in the README file
> Improve Grammar and Fix typos

- src/MurugoAuthHandler.php
Support a way to set dynamic redirect URLs in the Murugo auth package.
Note that, the mechanism to pick the redirect URL to be used is not handled by the package instead it is the responsibility of the Backend which is integrating the Murugo Auth Package.
- From the client side, the needed redirect URL can be sent to the backend which integrates Murugo Auth
- This feature is supported both by the stateless and stateful authentication mechanisms
- To use the dynamic URL, it should be part of the passport client configuration redirect URLs (which are comma separated on the OAUTH server)
- Next up, we'll need to call the `setRedirectUrl` in the following ways:
1) Redirection Init : `MurugoAuth::setRedirectUrl($request->redirect_url)->redirect();`
2) Redirection Callback: …
> fix: redirect - support dynamic redirect urls in the murugo auth package
